#!/usr/bin/env python3
"""
🔄 YouTube Cookies Auto-Refresh Script
========================================
Uses Playwright (headless Chromium on the server) to get fresh YouTube cookies
every time it runs. Cookies are tied to the server's IP and last longer than
cookies exported from another machine.

Setup:
  1. First-time login (requires manual auth):
     python3 youtube_auth.py --headless
     # Follow instructions to log in via SSH tunnel

  2. Then run this script every few hours via cron:
     0 */6 * * * root cd /opt/yt-audio-bot && /opt/yt-audio-bot/venv/bin/python3 cookies_refresh.py

  3. Or run it once right now:
     python3 cookies_refresh.py

The script:
  - Launches headless Chromium via Playwright
  - Visits youtube.com
  - Saves all YouTube/Google cookies to /opt/yt-audio-bot/cookies.txt
  - If logged in: saves auth cookies too
  - If not logged in: saves session cookies (still better than nothing)
"""

import os
import sys
import json
import logging
import traceback
from datetime import datetime

COOKIES_FILE = os.environ.get("YT_AUDIO_COOKIES", "/opt/yt-audio-bot/cookies.txt")
COOKIES_BACKUP = COOKIES_FILE + ".bak"

logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)s [%(levelname)s] %(message)s",
)
log = logging.getLogger("cookies_refresh")


def cookie_to_netscape(c):
    """Convert Playwright cookie dict to Netscape format string."""
    domain = c.get("domain", "")
    if not domain.startswith("."):
        domain = "." + domain
    flag = "TRUE"
    path = c.get("path", "/")
    secure = "TRUE" if c.get("secure", False) else "FALSE"
    expires = int(c.get("expires", 0)) or 2147483647
    name = c.get("name", "")
    value = c.get("value", "")
    return f"{domain}\t{flag}\t{path}\t{secure}\t{expires}\t{name}\t{value}"


def main():
    log.info("🚀 Launching headless Chromium via Playwright...")

    try:
        from playwright.sync_api import sync_playwright
    except ImportError:
        log.error("❌ Playwright not installed. Run: pip install playwright && python3 -m playwright install chromium")
        sys.exit(1)

    try:
        with sync_playwright() as p:
            browser = p.chromium.launch(
                headless=True,
                args=[
                    "--no-sandbox",
                    "--disable-dev-shm-usage",
                    "--disable-gpu",
                ],
            )
            context = browser.new_context(
                viewport={"width": 1280, "height": 720},
            )
            page = context.new_page()

            # Visit YouTube
            log.info("🌐 Opening YouTube...")
            page.goto("https://www.youtube.com", wait_until="domcontentloaded", timeout=30000)
            page.wait_for_timeout(3000)  # Wait for JS to set cookies

            # Check login status
            login_status = page.evaluate("""() => {
                const avatar = document.querySelector('img[alt*="Avatar"], yt-common-avatar');
                const loginBtn = document.querySelector('a[href*="signin"]');
                if (avatar) return "logged_in";
                if (loginBtn) return "not_logged_in";
                return "unknown";
            }""")

            log.info(f"📊 Login status: {login_status}")

            # Get all cookies
            cookies = context.cookies()
            log.info(f"🍪 Total cookies: {len(cookies)}")

            # Filter YouTube/Google
            yt_cookies = [
                c for c in cookies
                if any(d in c.get("domain", "") for d in [".youtube", ".google"])
            ]
            log.info(f"🎯 YouTube/Google cookies: {len(yt_cookies)}")

            # Check for auth cookies
            cookie_names = [c["name"] for c in yt_cookies]
            has_auth = any(
                name in cookie_names
                for name in ["SAPISID", "__Secure-3PAPISID", "__Secure-YNID", "LSID", "SID"]
            )

            if has_auth:
                log.info("✅ Auth cookies present!")
            else:
                log.warning("⚠️  No auth cookies (not logged in). Session cookies still saved.")

            # Backup existing cookies
            if os.path.exists(COOKIES_FILE):
                try:
                    os.rename(COOKIES_FILE, COOKIES_BACKUP)
                    log.info(f"💾 Backed up old cookies to {COOKIES_BACKUP}")
                except OSError:
                    pass

            # Save in Netscape format
            with open(COOKIES_FILE, "w") as f:
                f.write("# Netscape HTTP Cookie File\n")
                f.write(f"# Generated by cookies_refresh.py\n")
                f.write(f"# {datetime.now().isoformat()}\n")
                f.write(f"# Login status: {login_status}\n\n")
                for c in yt_cookies:
                    f.write(cookie_to_netscape(c) + "\n")

            file_size = os.path.getsize(COOKIES_FILE)
            log.info(f"✅ Saved {len(yt_cookies)} cookies to {COOKIES_FILE} ({file_size:,} bytes)")

            context.close()
            browser.close()
            return True

    except Exception as e:
        log.error(f"❌ Error: {e}")
        log.debug(traceback.format_exc())

        # Restore backup if exists
        if os.path.exists(COOKIES_BACKUP) and not os.path.exists(COOKIES_FILE):
            try:
                os.rename(COOKIES_BACKUP, COOKIES_FILE)
                log.info("♻️ Restored backup cookies")
            except OSError:
                pass

        return False


if __name__ == "__main__":
    success = main()
    sys.exit(0 if success else 1)
