#!/usr/bin/env python3
"""
YouTube Authentication Helper for YTAudioBook Bot
=================================================
One-time setup: logs into YouTube on the server and saves cookies.

Usage:
  1. Run this script on the server:
     python3 youtube_auth.py --remote-debug-port=49222

  2. On YOUR local machine (Mac), create an SSH tunnel:
     ssh -L 49222:127.0.0.1:49222 root@rom.zwitch.ru

  3. Open Chrome on your Mac and go to:
     http://127.0.0.1:49222

  4. You'll see the server's remote Chromium. Navigate to youtube.com
     and log in with your Google account.

  5. Close the browser window. The script will save cookies to
     /opt/yt-audio-bot/cookies.txt

  6. Restart the bot:
     systemctl restart yt-audio-bot
"""

import os
import sys
import json
import time
import signal
import logging
import argparse
import subprocess
from datetime import datetime

logging.basicConfig(level=logging.INFO, format="[%(levelname)s] %(message)s")
log = logging.getLogger("youtube_auth")

COOKIES_OUTPUT = "/opt/yt-audio-bot/cookies.txt"
CHROMIUM_PROFILE = "/opt/chromium-bot-profile"


def netscape_cookie(c) -> str:
    """Convert a Playwright cookie dict to Netscape format string."""
    domain = c.get("domain", "")
    # Ensure domain starts with .
    if not domain.startswith("."):
        domain = "." + domain
    flag = "TRUE"  # include subdomains
    path = c.get("path", "/")
    secure = "TRUE" if c.get("secure", False) else "FALSE"
    expires = int(c.get("expires", 0)) or 2147483647  # far future
    name = c.get("name", "")
    value = c.get("value", "")
    return f"{domain}\t{flag}\t{path}\t{secure}\t{expires}\t{name}\t{value}"


def save_cookies_netscape(cookies, filepath):
    """Save cookies in Netscape format for yt-dlp."""
    with open(filepath, "w") as f:
        f.write("# Netscape HTTP Cookie File\n")
        f.write("# Generated by youtube_auth.py\n")
        f.write(f"# {datetime.now().isoformat()}\n\n")
        for c in cookies:
            # Only save YouTube and google.com cookies
            domain = c.get("domain", "")
            if any(d in domain for d in [".youtube.com", ".google.com", "youtube.com", "google.com"]):
                line = netscape_cookie(c)
                f.write(line + "\n")
    log.info(f"✅ Saved {sum(1 for c in cookies if any(d in c.get('domain','') for d in ['.youtube','.google']))} YouTube/Google cookies to {filepath}")


def main():
    parser = argparse.ArgumentParser(description="YouTube Auth Helper")
    parser.add_argument("--remote-debug-port", type=int, default=49222,
                        help="Port for Chrome remote debugging (default: 49222)")
    parser.add_argument("--headless", action="store_true",
                        help="Run in headless mode (no visible window)")
    args = parser.parse_args()

    port = args.remote_debug_port
    log.info("🚀 Starting Chromium via Playwright...")

    from playwright.sync_api import sync_playwright

    with sync_playwright() as p:
        # Launch Chromium with remote debugging
        browser = p.chromium.launch(
            headless=args.headless,
            args=[
                f"--remote-debugging-port={port}",
                "--no-sandbox",
                "--disable-dev-shm-usage",
                "--disable-gpu",
            ],
        )
        context = browser.new_context(
            viewport={"width": 1280, "height": 800},
            storage_state=None,
        )

        page = context.new_page()

        log.info(f"🔗 Remote debugging: http://127.0.0.1:{port}")
        log.info(f"📌 To connect from your Mac, run:")
        log.info(f"    ssh -L {port}:127.0.0.1:{port} root@rom.zwitch.ru")
        log.info(f"   Then open http://127.0.0.1:{port} in Chrome")
        log.info("")
        log.info("🌐 Navigating to YouTube...")
        page.goto("https://www.youtube.com", wait_until="domcontentloaded")
        log.info("📄 YouTube loaded. Checking login status...")

        # Check if already logged in
        time.sleep(3)
        login_check = page.evaluate("""() => {
            const avatar = document.querySelector('img[alt*="Avatar"], yt-common-avatar');
            const buttons = document.querySelectorAll('a[href^="/logout"], a[href*="signout"]');
            const loginBtn = document.querySelector('a[href*="signin"]');
            if (avatar || buttons.length > 0) return "logged_in";
            if (loginBtn) return "not_logged_in";
            return "unknown";
        }""")

        if login_check == "logged_in":
            log.info("✅ Already logged in! Saving cookies...")
            cookies = context.cookies()
            save_cookies_netscape(cookies, COOKIES_OUTPUT)
            log.info("🎉 Done! Restart the bot: systemctl restart yt-audio-bot")
        else:
            log.warning("⚠️  Not logged in.")
            log.info("")
            log.info("=" * 60)
            log.info("🔑 LOGIN INSTRUCTIONS:")
            log.info("=" * 60)
            log.info(f"1. Open ANOTHER terminal and run:")
            log.info(f"   ssh -L {port}:127.0.0.1:{port} root@rom.zwitch.ru")
            log.info(f"")
            log.info(f"2. Open Chrome on your Mac and go to:")
            log.info(f"   http://127.0.0.1:{port}")
            log.info(f"")
            log.info(f"3. You'll see the server's remote browser window.")
            log.info(f"   Go to youtube.com and log in.")
            log.info(f"")
            log.info(f"4. After logging in, come back to this terminal")
            log.info(f"   and press ENTER to save cookies.")
            log.info("=" * 60)

            input("⏎ Press ENTER after logging in...")

            # Re-check login status
            page.goto("https://www.youtube.com", wait_until="domcontentloaded")
            time.sleep(3)

            login_check2 = page.evaluate("""() => {
                const avatar = document.querySelector('img[alt*="Avatar"], yt-common-avatar');
                if (avatar) return "logged_in";
                const loginBtn = document.querySelector('a[href*="signin"]');
                if (loginBtn) return "not_logged_in";
                return "unknown";
            }""")

            if login_check2 == "logged_in":
                log.info("✅ Login successful! Saving cookies...")
            else:
                log.warning("⚠️  Still not logged in. Saving whatever cookies we have...")

            cookies = context.cookies()
            save_cookies_netscape(cookies, COOKIES_OUTPUT)
            if login_check2 == "logged_in":
                log.info("🎉 Cookies saved! Restart bot: systemctl restart yt-audio-bot")
            else:
                log.info("💡 Cookies saved. Try running the script again after logging in.")

        context.close()
        browser.close()


if __name__ == "__main__":
    main()
